#! /bin/bash

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

# Jarvice
export JXE_APP="illumina-dragen_4_0_3_13_g52a8599a"
export IMAGE_URI="us-docker.pkg.dev/jarvice/images/illumina-dragen:dev"

# Configuration
export OUTPUT_BUCKET=${PROJECT_ID}-output #

# System Config
export TRIGGER_FILE_NAME="START_PIPELINE"

# GCP
export GCLOUD_PROJECT=$PROJECT_ID
export GCLOUD_REGION=us-central1
export GCLOUD_ZONE=us-central1-a
export GCLOUD_IMAGE=atos-illumina-jxe-stub-rc
export GCLOUD_IMAGE_PROJECT=atos-illumina-public
export GCLOUD_BATCH_IMAGE_PROJECT=batch-custom-image
export GCLOUD_MACHINE=n1-standard-2
export GCLOUD_INSTANCE=dragen
export BUCKET_NAME=${PROJECT_ID}-sample-data
export GCLOUD_NETWORK=default
export GCLOUD_SUBNET=default
export JOB_NAME_SHORT="job-dragen"
export JOB_NAME="projects/${PROJECT_ID}/locations/${GCLOUD_REGION}/jobs/${JOB_NAME_SHORT}"
export SA_JOB_NAME=illumina-script-sa
export JOB_SERVICE_ACCOUNT=${SA_JOB_NAME}@${PROJECT_ID}.iam.gserviceaccount.com
export SA_NAME_STORAGE=storage-admin
export SA_EMAIL_STORAGE=${SA_NAME_STORAGE}@${PROJECT_ID}.iam.gserviceaccount.com

# Secrets
export S3_SECRET="s3_hmac_secret_key"
export LICENCE_SECRET="license_secret_key"

# Cloud Function Params
export SOURCE_DIR="${DIR}/cloud_function"  # Cloud Function Directory - relative (main.py)
export SOURCE_ENTRY_POINT='run_job' # Entry point for Cloud Function
export RUNTIME='python37' # The only properly Supported for Runtime Environment
export PUBSUB_COMMAND_TOPIC='dragen-trigger'
export CLOUD_FUNCTION_NAME='run_dragen_job'
export INPUT_BUCKET=${PROJECT_ID}-sample-data # used for triggering CF
export INGRESS_SETTINGS=internal-and-gclb

echo "Using PROJECT_ID=$PROJECT_ID"
